-- =============================================================================
-- SQL Schema Definition for Oracle Database (Updated for Realtime OM View)
-- Project: Number Verification System (NT SolutionX)
-- Prefix: ...
-- Description: Schema mapping MSISDN, ICCID, IMSI, Service Type, and Owner
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. DROP Existing Objects (Safe Cleanup)
-- -----------------------------------------------------------------------------
DECLARE
   v_count NUMBER;
BEGIN
    -- Drop View NV_OM_NUMBER_REGISTRY if exists
    SELECT COUNT(*) INTO v_count FROM user_views WHERE view_name = 'NV_OM_NUMBER_REGISTRY';
    IF v_count > 0 THEN
       EXECUTE IMMEDIATE 'DROP VIEW NV_OM_NUMBER_REGISTRY';
    END IF;

    -- Drop View NV_NUMBER_REGISTRY if exists
    SELECT COUNT(*) INTO v_count FROM user_views WHERE view_name = 'NV_NUMBER_REGISTRY';
    IF v_count > 0 THEN
       EXECUTE IMMEDIATE 'DROP VIEW NV_NUMBER_REGISTRY';
    END IF;

    -- Drop Table NV_NUMBER_REGISTRY if exists (in case it was a table previously)
    SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'NV_NUMBER_REGISTRY';
    IF v_count > 0 THEN
       EXECUTE IMMEDIATE 'DROP TABLE NV_NUMBER_REGISTRY CASCADE CONSTRAINTS';
    END IF;

    -- Drop Table NV_LOCAL_NUMBER_REGISTRY if exists
    SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'NV_LOCAL_NUMBER_REGISTRY';
    IF v_count > 0 THEN
       EXECUTE IMMEDIATE 'DROP TABLE NV_LOCAL_NUMBER_REGISTRY CASCADE CONSTRAINTS';
    END IF;

    -- Drop Table NV_SYNC_LOG
    SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'NV_SYNC_LOG';
    IF v_count > 0 THEN
       EXECUTE IMMEDIATE 'DROP TABLE NV_SYNC_LOG CASCADE CONSTRAINTS';
    END IF;

    -- Drop Table NV_SYSTEM_CONFIG
    SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'NV_SYSTEM_CONFIG';
    IF v_count > 0 THEN
       EXECUTE IMMEDIATE 'DROP TABLE NV_SYSTEM_CONFIG CASCADE CONSTRAINTS';
    END IF;

    -- Drop Database Link OM_INVDB_LINK if exists
    SELECT COUNT(*) INTO v_count FROM user_db_links WHERE db_link = 'OM_INVDB_LINK';
    IF v_count > 0 THEN
       EXECUTE IMMEDIATE 'DROP DATABASE LINK OM_INVDB_LINK';
    END IF;
END;
/

-- -----------------------------------------------------------------------------
-- 2. CREATE Database Link to OM Database (INVDB)
-- -----------------------------------------------------------------------------
CREATE DATABASE LINK OM_INVDB_LINK 
CONNECT TO invuser IDENTIFIED BY xjfeil92 
USING '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=10.36.1.51)(PORT=1521))(CONNECT_DATA=(SID=INVDB)))';

-- -----------------------------------------------------------------------------
-- 3. CREATE Tables, Constraints & Views
-- -----------------------------------------------------------------------------

-- Table A: NV_LOCAL_NUMBER_REGISTRY (ตารางเก็บหมายเลขที่ลงทะเบียน/นำเข้าภายในระบบ)
CREATE TABLE NV_LOCAL_NUMBER_REGISTRY (
    ID                  NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    MSISDN              VARCHAR2(20) NOT NULL,
    ICCID               VARCHAR2(30) NOT NULL,
    IMSI                VARCHAR2(30) NOT NULL,
    SERVICE_TYPE        VARCHAR2(20),
    OWNER               VARCHAR2(100),
    STATUS              VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,
    CREATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    REMARKS             VARCHAR2(250),
    
    -- Constraints
    CONSTRAINT CK_NV_LOC_STATUS CHECK (STATUS IN ('AVAILABLE', 'ACTIVE', 'RESERVED', 'SUSPENDED'))
);

COMMENT ON TABLE NV_LOCAL_NUMBER_REGISTRY IS 'ตารางเก็บหมายเลขที่ลงทะเบียน/นำเข้าภายในระบบ (Local Identifier Registry)';
COMMENT ON COLUMN NV_LOCAL_NUMBER_REGISTRY.ID IS 'รหัสลำดับรายการอัตโนมัติ (Identity)';
COMMENT ON COLUMN NV_LOCAL_NUMBER_REGISTRY.MSISDN IS 'หมายเลขโทรศัพท์มือถือ (MSISDN)';
COMMENT ON COLUMN NV_LOCAL_NUMBER_REGISTRY.ICCID IS 'รหัสซิสการ์ด 19 หลัก (ICCID)';
COMMENT ON COLUMN NV_LOCAL_NUMBER_REGISTRY.IMSI IS 'รหัสระบุตัวตนผู้ใช้บริการในระบบโครงข่าย (IMSI)';
COMMENT ON COLUMN NV_LOCAL_NUMBER_REGISTRY.SERVICE_TYPE IS 'ประเภทบริการ (Prepaid/Postpaid)';
COMMENT ON COLUMN NV_LOCAL_NUMBER_REGISTRY.OWNER IS 'ชื่อผู้ถือครองสิทธิ์/ผู้ได้รับสิทธิ์';
COMMENT ON COLUMN NV_LOCAL_NUMBER_REGISTRY.STATUS IS 'สถานะในระบบ (AVAILABLE, ACTIVE, RESERVED, SUSPENDED)';
COMMENT ON COLUMN NV_LOCAL_NUMBER_REGISTRY.CREATED_AT IS 'วันเวลาบันทึกรายการ';
COMMENT ON COLUMN NV_LOCAL_NUMBER_REGISTRY.UPDATED_AT IS 'วันเวลาอัปเดตข้อมูลล่าสุด';

-- View B: NV_OM_NUMBER_REGISTRY (วิวเสมือนดึงเบอร์จาก OM โดยตรงแบบ Real-time)
CREATE OR REPLACE VIEW NV_OM_NUMBER_REGISTRY AS
SELECT 
    m.MASTER_ID as ID,
    m.EXTERNAL_ID as MSISDN,
    NVL(m.SECONDARY_CODE, '-') as ICCID,
    NVL(m.IMSI, '-') as IMSI,
    CASE WHEN m.NUMBER_TYPE = '2' THEN 'Postpaid' ELSE 'Prepaid' END as SERVICE_TYPE,
    TO_CHAR(p.OWNER) as OWNER,
    CASE 
        WHEN p.STATUS = 16 OR p.STATUS = 2 THEN 'ACTIVE'
        WHEN p.STATUS = 8 THEN 'RESERVED'
        WHEN p.STATUS = 15 THEN 'SUSPENDED'
        ELSE 'AVAILABLE'
    END as STATUS,
    NVL(p.UPDATED_DATE, m.UPDATED_DATE) as UPDATED_AT,
    'Realtime OM Number' as REMARKS
FROM INV_MASTER@OM_INVDB_LINK m
LEFT JOIN INV_MASTER_PROFILE@OM_INVDB_LINK p ON m.MASTER_ID = p.MASTER_ID
WHERE m.IS_ACTIVE = 'Y' AND (p.IS_ACTIVE = 'Y' OR p.IS_ACTIVE IS NULL)
  AND m.EXTERNAL_ID IS NOT NULL AND m.MVNO_ID = '89';

-- View C: NV_NUMBER_REGISTRY (วิวรวมดึงเบอร์จาก OM และระบบจำลองโลคอลเข้าด้วยกัน)
CREATE OR REPLACE VIEW NV_NUMBER_REGISTRY AS
SELECT 
    ID,
    MSISDN,
    ICCID,
    IMSI,
    SERVICE_TYPE,
    OWNER,
    STATUS,
    UPDATED_AT,
    REMARKS
FROM NV_OM_NUMBER_REGISTRY
UNION ALL
SELECT 
    ID,
    MSISDN,
    ICCID,
    IMSI,
    SERVICE_TYPE,
    OWNER,
    STATUS,
    UPDATED_AT,
    REMARKS
FROM NV_LOCAL_NUMBER_REGISTRY;

-- Table D: NV_SYNC_LOG (ตารางบันทึกประวัติการซิงก์ข้อมูล Reconciliation)

CREATE TABLE NV_SYNC_LOG (
    LOG_ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SYNC_TIME           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    TOTAL_RECORDS       NUMBER(10) DEFAULT 0 NOT NULL,
    SYNCED_RECORDS      NUMBER(10) DEFAULT 0 NOT NULL,
    FAILED_RECORDS      NUMBER(10) DEFAULT 0 NOT NULL,
    SYNC_STATUS         VARCHAR2(20) NOT NULL,
    ERROR_MESSAGE       VARCHAR2(4000),
    
    CONSTRAINT CK_NV_SYNC_STATUS CHECK (SYNC_STATUS IN ('SUCCESS', 'FAILED'))
);

-- Table D: NV_SYSTEM_CONFIG (ตารางเก็บพารามิเตอร์และการตั้งค่าระบบ)
CREATE TABLE NV_SYSTEM_CONFIG (
    CONFIG_KEY          VARCHAR2(50) PRIMARY KEY,
    CONFIG_VALUE        VARCHAR2(250) NOT NULL,
    DESCRIPTION         VARCHAR2(500),
    UPDATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

-- -----------------------------------------------------------------------------
-- 4. CREATE Indexes for Query Optimization on Local Table
-- -----------------------------------------------------------------------------
CREATE INDEX IDX_NV_LOC_MSISDN ON NV_LOCAL_NUMBER_REGISTRY (MSISDN);
CREATE INDEX IDX_NV_LOC_ICCID ON NV_LOCAL_NUMBER_REGISTRY (ICCID);
CREATE INDEX IDX_NV_LOC_STATUS ON NV_LOCAL_NUMBER_REGISTRY (STATUS);
CREATE INDEX IDX_NV_SYNC_TIME ON NV_SYNC_LOG (SYNC_TIME DESC);

-- -----------------------------------------------------------------------------
-- 5. CREATE Automatic Update Trigger (for Oracle timestamps)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_NV_LOCAL_REGISTRY_UPD
BEFORE UPDATE ON NV_LOCAL_NUMBER_REGISTRY
FOR EACH ROW
BEGIN
   :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_NV_SYSTEM_CONFIG_UPD
BEFORE UPDATE ON NV_SYSTEM_CONFIG
FOR EACH ROW
BEGIN
   :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- -----------------------------------------------------------------------------
-- 6. INSERT Initial Configuration & Seed Data
-- -----------------------------------------------------------------------------

-- System Configuration Seed
INSERT INTO NV_SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION)
VALUES ('sync_interval', 'daily', 'ความถี่ในการอัปเดตระบบอัตโนมัติ (hourly | daily | weekly)');

INSERT INTO NV_SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION)
VALUES ('batch_size_limit', '500', 'ขนาดจำกัดข้อมูลการซิงก์ข้อมูลต่อหนึ่งรอบการทำงาน');

INSERT INTO NV_SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION)
VALUES ('auto_repair_enabled', 'true', 'เปิดใช้งานการแก้ปัญหาและจับคู่เบอร์ซ้ำอัตโนมัติ (true | false)');

INSERT INTO NV_SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION)
VALUES ('notify_email', 'intranet-admin@ntsolutionx.co.th', 'อีเมลแจ้งเตือนเมื่อระบบ Reconciliation ทำงานล้มเหลว');

-- Identifiers Seed for Local Registry Table (so they are UNION'ed and visible)
INSERT INTO NV_LOCAL_NUMBER_REGISTRY (MSISDN, ICCID, IMSI, SERVICE_TYPE, OWNER, STATUS, REMARKS)
VALUES ('190170010', '8966002301120000001', '520001919998326', 'Prepaid', 'ให้ NT', 'ACTIVE', 'Excel Row 1');

INSERT INTO NV_LOCAL_NUMBER_REGISTRY (MSISDN, ICCID, IMSI, SERVICE_TYPE, OWNER, STATUS, REMARKS)
VALUES ('190170011', '8966002301120000002', '520001919998327', 'Prepaid', 'ให้ NT', 'ACTIVE', 'Excel Row 2');

INSERT INTO NV_LOCAL_NUMBER_REGISTRY (MSISDN, ICCID, IMSI, SERVICE_TYPE, OWNER, STATUS, REMARKS)
VALUES ('190170012', '8966002301120000003', '520001919998328', 'Prepaid', 'ให้ NT', 'ACTIVE', 'Excel Row 3');

INSERT INTO NV_LOCAL_NUMBER_REGISTRY (MSISDN, ICCID, IMSI, SERVICE_TYPE, OWNER, STATUS, REMARKS)
VALUES ('190170013', '8966002301120000004', '520001919998329', NULL, 'ให้ NT', 'ACTIVE', 'Excel Row 4 (No service type)');

INSERT INTO NV_LOCAL_NUMBER_REGISTRY (MSISDN, ICCID, IMSI, SERVICE_TYPE, OWNER, STATUS, REMARKS)
VALUES ('190170014', '8966002301120000005', '520001919998330', 'Prepaid', 'ให้ NT', 'ACTIVE', 'Excel Row 5');

INSERT INTO NV_LOCAL_NUMBER_REGISTRY (MSISDN, ICCID, IMSI, SERVICE_TYPE, OWNER, STATUS, REMARKS)
VALUES ('190170015', '8966002301120000006', '520001919998331', 'Prepaid', 'ให้ NT', 'ACTIVE', 'Excel Row 6');

INSERT INTO NV_LOCAL_NUMBER_REGISTRY (MSISDN, ICCID, IMSI, SERVICE_TYPE, OWNER, STATUS, REMARKS)
VALUES ('190170016', '8966002301120000007', '520001919998332', 'Prepaid', 'นิค', 'ACTIVE', 'Excel Row 7');

INSERT INTO NV_LOCAL_NUMBER_REGISTRY (MSISDN, ICCID, IMSI, SERVICE_TYPE, OWNER, STATUS, REMARKS)
VALUES ('190170017', '8966002301120000008', '520001919998333', 'Prepaid', 'ให้ NT', 'ACTIVE', 'Excel Row 8');

INSERT INTO NV_LOCAL_NUMBER_REGISTRY (MSISDN, ICCID, IMSI, SERVICE_TYPE, OWNER, STATUS, REMARKS)
VALUES ('190170018', '8966002301120000009', '520001919998334', 'Prepaid', 'ให้ NT', 'ACTIVE', 'Excel Row 9');

INSERT INTO NV_LOCAL_NUMBER_REGISTRY (MSISDN, ICCID, IMSI, SERVICE_TYPE, OWNER, STATUS, REMARKS)
VALUES ('190170019', '89660023011200000010', '520001919998335', 'Prepaid', 'ให้ NT', 'ACTIVE', 'Excel Row 10');

COMMIT;

-- -----------------------------------------------------------------------------
-- End of SQL Script
-- -----------------------------------------------------------------------------
