-- =============================================================================
-- SQL Schema Definition for Oracle Database
-- Project: Number Verification System (NT SolutionX)
-- Prefix: NV_
-- Description: Schema for managing Master Number database records (MSISDN & ICCID)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. DROP Existing Objects (Safe Cleanup)
-- -----------------------------------------------------------------------------
DECLARE
   v_count NUMBER;
BEGIN
   -- Drop Table NV_NUMBER_REGISTRY
   SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'NV_NUMBER_REGISTRY';
   IF v_count > 0 THEN
      EXECUTE IMMEDIATE 'DROP TABLE NV_NUMBER_REGISTRY CASCADE CONSTRAINTS';
   END IF;

   -- Drop Table NV_SYNC_LOG
   SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'NV_SYNC_LOG';
   IF v_count > 0 THEN
      EXECUTE IMMEDIATE 'DROP TABLE NV_SYNC_LOG CASCADE CONSTRAINTS';
   END IF;

   -- Drop Table NV_SYSTEM_CONFIG
   SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'NV_SYSTEM_CONFIG';
   IF v_count > 0 THEN
      EXECUTE IMMEDIATE 'DROP TABLE NV_SYSTEM_CONFIG CASCADE CONSTRAINTS';
   END IF;
END;
/

-- -----------------------------------------------------------------------------
-- 2. CREATE Tables & Constraints
-- -----------------------------------------------------------------------------

-- Table A: NV_NUMBER_REGISTRY (ตารางเก็บหมายเลขโทรศัพท์และซิมการ์ด)
CREATE TABLE NV_NUMBER_REGISTRY (
    ID                  NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    IDENTIFIER_NO       VARCHAR2(30) NOT NULL,
    IDENTIFIER_TYPE     VARCHAR2(10) NOT NULL,
    SIM_CATEGORY        VARCHAR2(15) DEFAULT 'Prepaid' NOT NULL,
    SOURCE_SYSTEM       VARCHAR2(30) DEFAULT 'Oracle DB' NOT NULL,
    STATUS              VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,
    CREATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    REMARKS             VARCHAR2(250),
    
    -- Constraints
    CONSTRAINT UQ_NV_IDENTIFIER UNIQUE (IDENTIFIER_NO),
    CONSTRAINT CK_NV_IDENTIFIER_TYPE CHECK (IDENTIFIER_TYPE IN ('MSISDN', 'ICCID')),
    CONSTRAINT CK_NV_SIM_CATEGORY CHECK (SIM_CATEGORY IN ('Prepaid', 'Postpaid')),
    CONSTRAINT CK_NV_STATUS CHECK (STATUS IN ('AVAILABLE', 'ACTIVE', 'RESERVED', 'SUSPENDED'))
);

COMMENT ON TABLE NV_NUMBER_REGISTRY IS 'ตารางเก็บหมายเลขและรหัสอุปกรณ์หลัก (Master Identifier Registry)';
COMMENT ON COLUMN NV_NUMBER_REGISTRY.ID IS 'รหัสลำดับรายการอัตโนมัติ (Identity)';
COMMENT ON COLUMN NV_NUMBER_REGISTRY.IDENTIFIER_NO IS 'หมายเลขโทรศัพท์ (MSISDN) หรือรหัสซิสการ์ด (ICCID)';
COMMENT ON COLUMN NV_NUMBER_REGISTRY.IDENTIFIER_TYPE IS 'ประเภทของหมายเลข (MSISDN, ICCID)';
COMMENT ON COLUMN NV_NUMBER_REGISTRY.SIM_CATEGORY IS 'ประเภทซิมการ์ด (Prepaid: เติมเงิน, Postpaid: รายเดือน)';
COMMENT ON COLUMN NV_NUMBER_REGISTRY.SOURCE_SYSTEM IS 'ระบบต้นทางของข้อมูล (เช่น Oracle DB)';
COMMENT ON COLUMN NV_NUMBER_REGISTRY.STATUS IS 'สถานะปัจจุบันของเบอร์ (AVAILABLE: ว่างพร้อมขาย, ACTIVE: เปิดใช้งานแล้ว)';
COMMENT ON COLUMN NV_NUMBER_REGISTRY.CREATED_AT IS 'วันเวลาที่บันทึกข้อมูลเข้าระบบ';
COMMENT ON COLUMN NV_NUMBER_REGISTRY.UPDATED_AT IS 'วันเวลาที่อัปเดตข้อมูลล่าสุด';


-- Table B: NV_SYNC_LOG (ตารางบันทึกประวัติการซิงก์ข้อมูล Reconciliation)
CREATE TABLE NV_SYNC_LOG (
    LOG_ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SYNC_TIME           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    TOTAL_RECORDS       NUMBER(10) DEFAULT 0 NOT NULL,
    SYNCED_RECORDS      NUMBER(10) DEFAULT 0 NOT NULL,
    FAILED_RECORDS      NUMBER(10) DEFAULT 0 NOT NULL,
    SYNC_STATUS         VARCHAR2(20) NOT NULL,
    ERROR_MESSAGE       VARCHAR2(4000),
    
    CONSTRAINT CK_NV_SYNC_STATUS CHECK (SYNC_STATUS IN ('SUCCESS', 'FAILED'))
);

COMMENT ON TABLE NV_SYNC_LOG IS 'ประวัติตรวจสอบความเข้ากันของข้อมูล (Sync Reconciliation Log)';


-- Table C: NV_SYSTEM_CONFIG (ตารางเก็บพารามิเตอร์และการตั้งค่าระบบ)
CREATE TABLE NV_SYSTEM_CONFIG (
    CONFIG_KEY          VARCHAR2(50) PRIMARY KEY,
    CONFIG_VALUE        VARCHAR2(250) NOT NULL,
    DESCRIPTION         VARCHAR2(500),
    UPDATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON TABLE NV_SYSTEM_CONFIG IS 'ตารางการตั้งค่าพารามิเตอร์ในระบบข้อมูลหลัก';

-- -----------------------------------------------------------------------------
-- 3. CREATE Indexes for Query Optimization
-- -----------------------------------------------------------------------------
CREATE INDEX IDX_NV_REG_IDENTIFIER ON NV_NUMBER_REGISTRY (IDENTIFIER_NO);
CREATE INDEX IDX_NV_REG_TYPE_STATUS ON NV_NUMBER_REGISTRY (IDENTIFIER_TYPE, STATUS);
CREATE INDEX IDX_NV_SYNC_TIME ON NV_SYNC_LOG (SYNC_TIME DESC);

-- -----------------------------------------------------------------------------
-- 4. CREATE Automatic Update Trigger (for Oracle timestamps)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_NV_NUMBER_REGISTRY_UPD
BEFORE UPDATE ON NV_NUMBER_REGISTRY
FOR EACH ROW
BEGIN
   :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_NV_SYSTEM_CONFIG_UPD
BEFORE UPDATE ON NV_SYSTEM_CONFIG
FOR EACH ROW
BEGIN
   :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- -----------------------------------------------------------------------------
-- 5. INSERT Initial Configuration & Seed Data (Mock)
-- -----------------------------------------------------------------------------

-- System Configuration Seed
INSERT INTO NV_SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION)
VALUES ('sync_interval', 'daily', 'ความถี่ในการอัปเดตระบบอัตโนมัติ (hourly | daily | weekly)');

INSERT INTO NV_SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION)
VALUES ('batch_size_limit', '500', 'ขนาดจำกัดข้อมูลการซิงก์ข้อมูลต่อหนึ่งรอบการทำงาน');

INSERT INTO NV_SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION)
VALUES ('auto_repair_enabled', 'true', 'เปิดใช้งานการแก้ปัญหาและจับคู่เบอร์ซ้ำอัตโนมัติ (true | false)');

INSERT INTO NV_SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION)
VALUES ('notify_email', 'intranet-admin@ntsolutionx.co.th', 'อีเมลแจ้งเตือนเมื่อระบบ Reconciliation ทำงานล้มเหลว');

-- Identifiers Seed (Mock Data matching frontend lists)
-- MSISDNs
INSERT INTO NV_NUMBER_REGISTRY (IDENTIFIER_NO, IDENTIFIER_TYPE, SIM_CATEGORY, STATUS, REMARKS)
VALUES ('0819005522', 'MSISDN', 'Prepaid', 'ACTIVE', 'นำเข้าระบบทดสอบแรกเริ่ม');

INSERT INTO NV_NUMBER_REGISTRY (IDENTIFIER_NO, IDENTIFIER_TYPE, SIM_CATEGORY, STATUS, REMARKS)
VALUES ('0819005523', 'MSISDN', 'Postpaid', 'AVAILABLE', 'เบอร์ยังไม่ได้จดทะเบียน');

INSERT INTO NV_NUMBER_REGISTRY (IDENTIFIER_NO, IDENTIFIER_TYPE, SIM_CATEGORY, STATUS, REMARKS)
VALUES ('0819005524', 'MSISDN', 'Prepaid', 'ACTIVE', 'ลูกค้าเปิดเบอร์ใช้งานปกติ');

INSERT INTO NV_NUMBER_REGISTRY (IDENTIFIER_NO, IDENTIFIER_TYPE, SIM_CATEGORY, STATUS, REMARKS)
VALUES ('0819005525', 'MSISDN', 'Prepaid', 'AVAILABLE', 'เบอร์พักสถานะจำหน่าย');

INSERT INTO NV_NUMBER_REGISTRY (IDENTIFIER_NO, IDENTIFIER_TYPE, SIM_CATEGORY, STATUS, REMARKS)
VALUES ('0819005526', 'MSISDN', 'Postpaid', 'ACTIVE', 'สัญญาแพ็คเกจผูกบริการรายเดือน');

-- ICCIDs (Sim Card Serials)
INSERT INTO NV_NUMBER_REGISTRY (IDENTIFIER_NO, IDENTIFIER_TYPE, SIM_CATEGORY, STATUS, REMARKS)
VALUES ('8966031122334455667', 'ICCID', 'Prepaid', 'ACTIVE', 'ซิมการ์ดผูกเบอร์ Prepaid');

INSERT INTO NV_NUMBER_REGISTRY (IDENTIFIER_NO, IDENTIFIER_TYPE, SIM_CATEGORY, STATUS, REMARKS)
VALUES ('8966031122334455668', 'ICCID', 'Prepaid', 'AVAILABLE', 'ซิมการ์ดเปล่าในคลังสินค้า');

COMMIT;

-- -----------------------------------------------------------------------------
-- End of SQL Script
-- -----------------------------------------------------------------------------
