-- =============================================================================
-- SQL Schema Definition for Oracle Database (Updated)
-- Project: Number Verification System (NT SolutionX)
-- Prefix: NV_
-- Description: Schema mapping MSISDN, ICCID, IMSI, Service Type, and Owner
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. DROP Existing Objects (Safe Cleanup)
-- -----------------------------------------------------------------------------
DECLARE
   v_count NUMBER;
BEGIN
   -- Drop Table NV_NUMBER_REGISTRY
   SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'NV_NUMBER_REGISTRY';
   IF v_count > 0 THEN
      EXECUTE IMMEDIATE 'DROP TABLE NV_NUMBER_REGISTRY CASCADE CONSTRAINTS';
   END IF;

   -- Drop Table NV_SYNC_LOG
   SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'NV_SYNC_LOG';
   IF v_count > 0 THEN
      EXECUTE IMMEDIATE 'DROP TABLE NV_SYNC_LOG CASCADE CONSTRAINTS';
   END IF;

   -- Drop Table NV_SYSTEM_CONFIG
   SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'NV_SYSTEM_CONFIG';
   IF v_count > 0 THEN
      EXECUTE IMMEDIATE 'DROP TABLE NV_SYSTEM_CONFIG CASCADE CONSTRAINTS';
   END IF;
END;
/

-- -----------------------------------------------------------------------------
-- 2. CREATE Tables & Constraints
-- -----------------------------------------------------------------------------

-- Table A: NV_NUMBER_REGISTRY (ตารางข้อมูลหลักที่ผูกหมายเลขและซิมการ์ดเข้าด้วยกัน)
CREATE TABLE NV_NUMBER_REGISTRY (
    ID                  NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    MSISDN              VARCHAR2(20) NOT NULL,
    ICCID               VARCHAR2(30) NOT NULL,
    IMSI                VARCHAR2(30) NOT NULL,
    SERVICE_TYPE        VARCHAR2(20) DEFAULT 'Prepaid',
    OWNER               VARCHAR2(100),
    STATUS              VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL,
    CREATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    REMARKS             VARCHAR2(250),
    
    -- Constraints (ป้องกันข้อมูลซ้ำซ้อน)
    CONSTRAINT UQ_NV_MSISDN UNIQUE (MSISDN),
    CONSTRAINT UQ_NV_ICCID UNIQUE (ICCID),
    CONSTRAINT UQ_NV_IMSI UNIQUE (IMSI),
    CONSTRAINT CK_NV_STATUS CHECK (STATUS IN ('AVAILABLE', 'ACTIVE', 'RESERVED', 'SUSPENDED'))
);

COMMENT ON TABLE NV_NUMBER_REGISTRY IS 'ตารางเก็บหมายเลขและรหัสอุปกรณ์หลักที่ผูกกัน (Master Identifiers Registry)';
COMMENT ON COLUMN NV_NUMBER_REGISTRY.ID IS 'รหัสลำดับรายการอัตโนมัติ (Identity)';
COMMENT ON COLUMN NV_NUMBER_REGISTRY.MSISDN IS 'หมายเลขโทรศัพท์มือถือ (เช่น 190170010)';
COMMENT ON COLUMN NV_NUMBER_REGISTRY.ICCID IS 'รหัสซิสการ์ด 19 หลัก (เช่น 8966002301120000001)';
COMMENT ON COLUMN NV_NUMBER_REGISTRY.IMSI IS 'รหัสระบุตัวตนผู้ใช้บริการในระบบโครงข่าย (เช่น 520001919998326)';
COMMENT ON COLUMN NV_NUMBER_REGISTRY.SERVICE_TYPE IS 'ประเภทบริการ (เช่น Prepaid: เติมเงิน, Postpaid: รายเดือน)';
COMMENT ON COLUMN NV_NUMBER_REGISTRY.OWNER IS 'ชื่อผู้ถือครองสิทธิ์/ผู้ได้รับสิทธิ์ (เช่น ให้ NT, นิค)';
COMMENT ON COLUMN NV_NUMBER_REGISTRY.STATUS IS 'สถานะในระบบ (AVAILABLE, ACTIVE, RESERVED)';
COMMENT ON COLUMN NV_NUMBER_REGISTRY.CREATED_AT IS 'วันเวลาบันทึกรายการ';
COMMENT ON COLUMN NV_NUMBER_REGISTRY.UPDATED_AT IS 'วันเวลาอัปเดตข้อมูลล่าสุด';


-- Table B: NV_SYNC_LOG (ตารางบันทึกประวัติการซิงก์ข้อมูล Reconciliation)
CREATE TABLE NV_SYNC_LOG (
    LOG_ID              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SYNC_TIME           TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    TOTAL_RECORDS       NUMBER(10) DEFAULT 0 NOT NULL,
    SYNCED_RECORDS      NUMBER(10) DEFAULT 0 NOT NULL,
    FAILED_RECORDS      NUMBER(10) DEFAULT 0 NOT NULL,
    SYNC_STATUS         VARCHAR2(20) NOT NULL,
    ERROR_MESSAGE       VARCHAR2(4000),
    
    CONSTRAINT CK_NV_SYNC_STATUS CHECK (SYNC_STATUS IN ('SUCCESS', 'FAILED'))
);

COMMENT ON TABLE NV_SYNC_LOG IS 'ประวัติตรวจสอบความเข้ากันของข้อมูล (Sync Reconciliation Log)';


-- Table C: NV_SYSTEM_CONFIG (ตารางเก็บพารามิเตอร์และการตั้งค่าระบบ)
CREATE TABLE NV_SYSTEM_CONFIG (
    CONFIG_KEY          VARCHAR2(50) PRIMARY KEY,
    CONFIG_VALUE        VARCHAR2(250) NOT NULL,
    DESCRIPTION         VARCHAR2(500),
    UPDATED_AT          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

COMMENT ON TABLE NV_SYSTEM_CONFIG IS 'ตารางการตั้งค่าพารามิเตอร์ในระบบข้อมูลหลัก';

-- -----------------------------------------------------------------------------
-- 3. CREATE Indexes for Query Optimization
-- -----------------------------------------------------------------------------
CREATE INDEX IDX_NV_REG_MSISDN ON NV_NUMBER_REGISTRY (MSISDN);
CREATE INDEX IDX_NV_REG_ICCID ON NV_NUMBER_REGISTRY (ICCID);
CREATE INDEX IDX_NV_REG_IMSI ON NV_NUMBER_REGISTRY (IMSI);
CREATE INDEX IDX_NV_REG_STATUS ON NV_NUMBER_REGISTRY (STATUS);
CREATE INDEX IDX_NV_SYNC_TIME ON NV_SYNC_LOG (SYNC_TIME DESC);

-- -----------------------------------------------------------------------------
-- 4. CREATE Automatic Update Trigger (for Oracle timestamps)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_NV_NUMBER_REGISTRY_UPD
BEFORE UPDATE ON NV_NUMBER_REGISTRY
FOR EACH ROW
BEGIN
   :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER TRG_NV_SYSTEM_CONFIG_UPD
BEFORE UPDATE ON NV_SYSTEM_CONFIG
FOR EACH ROW
BEGIN
   :NEW.UPDATED_AT := SYSTIMESTAMP;
END;
/

-- -----------------------------------------------------------------------------
-- 5. INSERT Initial Configuration & Seed Data (Mock from User Excel)
-- -----------------------------------------------------------------------------

-- System Configuration Seed
INSERT INTO NV_SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION)
VALUES ('sync_interval', 'daily', 'ความถี่ในการอัปเดตระบบอัตโนมัติ (hourly | daily | weekly)');

INSERT INTO NV_SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION)
VALUES ('batch_size_limit', '500', 'ขนาดจำกัดข้อมูลการซิงก์ข้อมูลต่อหนึ่งรอบการทำงาน');

INSERT INTO NV_SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION)
VALUES ('auto_repair_enabled', 'true', 'เปิดใช้งานการแก้ปัญหาและจับคู่เบอร์ซ้ำอัตโนมัติ (true | false)');

INSERT INTO NV_SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, DESCRIPTION)
VALUES ('notify_email', 'intranet-admin@ntsolutionx.co.th', 'อีเมลแจ้งเตือนเมื่อระบบ Reconciliation ทำงานล้มเหลว');

-- Identifiers Seed (Directly matched to User Excel Screenshot)
INSERT INTO NV_NUMBER_REGISTRY (MSISDN, ICCID, IMSI, SERVICE_TYPE, OWNER, STATUS, REMARKS)
VALUES ('190170010', '8966002301120000001', '520001919998326', 'Prepaid', 'ให้ NT', 'ACTIVE', 'Excel Row 1');

INSERT INTO NV_NUMBER_REGISTRY (MSISDN, ICCID, IMSI, SERVICE_TYPE, OWNER, STATUS, REMARKS)
VALUES ('190170011', '8966002301120000002', '520001919998327', 'Prepaid', 'ให้ NT', 'ACTIVE', 'Excel Row 2');

INSERT INTO NV_NUMBER_REGISTRY (MSISDN, ICCID, IMSI, SERVICE_TYPE, OWNER, STATUS, REMARKS)
VALUES ('190170012', '8966002301120000003', '520001919998328', 'Prepaid', 'ให้ NT', 'ACTIVE', 'Excel Row 3');

-- Row 4 has empty Service Type
INSERT INTO NV_NUMBER_REGISTRY (MSISDN, ICCID, IMSI, SERVICE_TYPE, OWNER, STATUS, REMARKS)
VALUES ('190170013', '8966002301120000004', '520001919998329', NULL, 'ให้ NT', 'ACTIVE', 'Excel Row 4 (No service type)');

INSERT INTO NV_NUMBER_REGISTRY (MSISDN, ICCID, IMSI, SERVICE_TYPE, OWNER, STATUS, REMARKS)
VALUES ('190170014', '8966002301120000005', '520001919998330', 'Prepaid', 'ให้ NT', 'ACTIVE', 'Excel Row 5');

INSERT INTO NV_NUMBER_REGISTRY (MSISDN, ICCID, IMSI, SERVICE_TYPE, OWNER, STATUS, REMARKS)
VALUES ('190170015', '8966002301120000006', '520001919998331', 'Prepaid', 'ให้ NT', 'ACTIVE', 'Excel Row 6');

-- Row 7 has Owner "นิค"
INSERT INTO NV_NUMBER_REGISTRY (MSISDN, ICCID, IMSI, SERVICE_TYPE, OWNER, STATUS, REMARKS)
VALUES ('190170016', '8966002301120000007', '520001919998332', 'Prepaid', 'นิค', 'ACTIVE', 'Excel Row 7');

INSERT INTO NV_NUMBER_REGISTRY (MSISDN, ICCID, IMSI, SERVICE_TYPE, OWNER, STATUS, REMARKS)
VALUES ('190170017', '8966002301120000008', '520001919998333', 'Prepaid', 'ให้ NT', 'ACTIVE', 'Excel Row 8');

INSERT INTO NV_NUMBER_REGISTRY (MSISDN, ICCID, IMSI, SERVICE_TYPE, OWNER, STATUS, REMARKS)
VALUES ('190170018', '8966002301120000009', '520001919998334', 'Prepaid', 'ให้ NT', 'ACTIVE', 'Excel Row 9');

INSERT INTO NV_NUMBER_REGISTRY (MSISDN, ICCID, IMSI, SERVICE_TYPE, OWNER, STATUS, REMARKS)
VALUES ('190170019', '89660023011200000010', '520001919998335', 'Prepaid', 'ให้ NT', 'ACTIVE', 'Excel Row 10');

COMMIT;

-- -----------------------------------------------------------------------------
-- End of SQL Script
-- -----------------------------------------------------------------------------
